config:
  state:
    backend: local
    options:
      stateFile: devstream.state
tools:
  - name: repo-scaffolding
    instanceID: myapp
    options:
      destinationRepo:
        org: [[env GITHUB_ORG]]
        name: [[env APP]]
        branch: main
        scmType: github
        token: [[env GITHUB_TOKEN]]
      sourceRepo:
        org: Ajay-Chidambaram
        name: port-idp-templates
        scmType: github
